# Generated by Django 4.2.7 on 2025-07-27 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StockAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker1", models.CharField(max_length=10)),
                ("ticker2", models.CharField(max_length=10)),
                (
                    "analysis_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("data_points", models.IntegerField()),
                (
                    "ticker1_current_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "ticker1_predicted_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "ticker2_current_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "ticker2_predicted_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("ticker1_mae", models.DecimalField(decimal_places=4, max_digits=10)),
                ("ticker1_mse", models.DecimalField(decimal_places=4, max_digits=10)),
                ("ticker1_rmse", models.DecimalField(decimal_places=4, max_digits=10)),
                ("ticker1_mape", models.DecimalField(decimal_places=4, max_digits=10)),
                ("ticker2_mae", models.DecimalField(decimal_places=4, max_digits=10)),
                ("ticker2_mse", models.DecimalField(decimal_places=4, max_digits=10)),
                ("ticker2_rmse", models.DecimalField(decimal_places=4, max_digits=10)),
                ("ticker2_mape", models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                "verbose_name_plural": "Stock Analyses",
                "ordering": ["-analysis_date"],
            },
        ),
    ]
